#!/bin/bash

if ! command -v flameshot &> /dev/null; then
    echo "Error: flameshot is not installed. Please install it and try again."
    exit 1
fi

screenshots_path="$HOME/Nextcloud/Screenshots"

if [ ! -d "$screenshots_path" ]; then
    echo "Warning: Screenshots folder does not exist. Screenshots will be saved without specifying a path."
fi

flameshot gui --clipboard $( [ -d "$screenshots_path" ] && echo "--path $screenshots_path" )
